=== irlandakelly/Base-de-datos-II/TareaBD1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT FACTURAS (FACTURA+)>
<!ELEMENT FACTURA (PRODUCTO+)>
<!ATTLIST FACTURA NUMEROFACTURA CDATA #REQUIRED>
<!ATTLIST FACTURA FECHA CDATA #REQUIRED>
<!ATTLIST FACTURA CLIENTE CDATA #REQUIRED>

<!ELEMENT PRODUCTO (#PCDATA)>
<!ATTLIST PRODUCTO CODIGO CDATA #REQUIRED>
<!ATTLIST PRODUCTO DESCRIPCION CDATA #REQUIRED>
<!ATTLIST PRODUCTO CANTIDAD CDATA #REQUIRED>
<!ATTLIST PRODUCTO PRECIO CDATA #REQUIRED>

=== irlandakelly/Base-de-datos-II/TareaBD1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FACTURAS SYSTEM "TareaBD1.dtd">
<FACTURAS>
    <FACTURA NUMEROFACTURA="1" FECHA="30-03-2022" CLIENTE="1">
        <PRODUCTO CODIGO="1" DESCRIPCION="LECHE" CANTIDAD="1" PRECIO="30"></PRODUCTO>
        <PRODUCTO CODIGO="2" DESCRIPCION="ARROZ" CANTIDAD="2" PRECIO="20"></PRODUCTO>
        <PRODUCTO CODIGO="3" DESCRIPCION="CEREAL" CANTIDAD="3" PRECIO="50"></PRODUCTO>
    </FACTURA>
    
    <FACTURA NUMEROFACTURA="2" FECHA="30-03-2022" CLIENTE="2">
        <PRODUCTO CODIGO="1" DESCRIPCION="LECHE" CANTIDAD="2" PRECIO="30"></PRODUCTO>
        <PRODUCTO CODIGO="5" DESCRIPCION="SABRITAS" CANTIDAD="1" PRECIO="25"></PRODUCTO>
    </FACTURA>
</FACTURAS>
